//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DB_Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Course_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course_details()
        {
            this.Enrollment_details = new HashSet<Enrollment_details>();
        }

        [Required]
        public int Id { get; set; }

        [Required(ErrorMessage = "Enter course name")]
        [Display(Name = "Course name")]
        public string CName { get; set; }

        [Required(ErrorMessage = "Enter the subjects")]
        [Display(Name = "Subjects")]
        public string CSub { get; set; }

        [Required(ErrorMessage = "Enter the course duration")]
        [Range(1,6,ErrorMessage ="Course duration should be within 1 to 6 months")]
        [Display(Name ="Duration (in months)")]
        public Nullable<int> CDuration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment_details> Enrollment_details { get; set; }
    }
}
