//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DB_Demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.ComponentModel.DataAnnotations;

    public partial class Vivekananda_SchoolEntities : DbContext
    {
        public Vivekananda_SchoolEntities()
            : base("name=Vivekananda_SchoolEntities")
        {
    }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
       
    
        public virtual DbSet<Course_details> Course_details { get; set; }
        public virtual DbSet<Enrollment_details> Enrollment_details { get; set; }
        public virtual DbSet<Student_VMHSS> Student_VMHSS { get; set; }
    }
}

