//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_Management
    {
        public int C_id { get; set; }
        public Nullable<int> Playerid { get; set; }
        public string position { get; set; }
        public Nullable<System.DateTime> Contracts { get; set; }
        public Nullable<System.DateTime> contracts_Left { get; set; }
    
        public virtual Player_Details Player_Details { get; set; }
        public virtual Position Position1 { get; set; }
    }
}
